id: 48fb916f186d43e5945498f8b72f76d5
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_384-Glorious_King_of_Tantras_That_Resolves_All_Secrets-v1
  language: bo
  author: ''
  volume: {}
